# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zhidaily', '0002_auto_20161119_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
