# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-19 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhidaily', '0003_auto_20161119_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='intro',
            field=models.CharField(blank=None, max_length=1000, null=None),
        ),
    ]
