# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.CharField(blank=True, choices=[('python', 'python'), ('web', 'web'), ('life', 'life')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
